version: "3.9"
services:
  app:
    image: ghcr.io/zareix/zrx-link
    ports:
      - "8170:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - EMAIL_SERVER=${EMAIL_SERVER}
      - EMAIL_FROM=${EMAIL_FROM}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
