version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
      - '80:80'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - PUBLIC_URL=http://localhost:3000
      - ADMIN_TOKEN=azerty

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
